# Generated by Django 5.2 on 2025-05-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('read', 'Lu'), ('answered', 'Répondu')], default='new', max_length=20, verbose_name='Statut')),
                ('admin_response', models.TextField(blank=True, null=True, verbose_name='Réponse')),
            ],
        ),
    ]
