# Generated by Django 5.2 on 2025-05-28 20:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ['name'], 'verbose_name': 'Acteur', 'verbose_name_plural': 'Acteurs'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-created_at'], 'verbose_name': 'Film/Série', 'verbose_name_plural': 'Films/Séries'},
        ),
        migrations.AddField(
            model_name='actor',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='actor',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nationalité'),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='content_type',
            field=models.CharField(choices=[('movie', 'Film'), ('series', 'Série')], default='movie', max_length=10, verbose_name='Type de contenu'),
        ),
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('ongoing', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='completed', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='movie',
            name='total_seasons',
            field=models.PositiveIntegerField(blank=True, help_text='Pour les séries uniquement', null=True, verbose_name='Nombre total de saisons'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Biographie'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(related_name='actors', to='movies.movie', verbose_name='Films/Séries'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='actors/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Bannière'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='categories',
            field=models.ManyToManyField(related_name='movies', to='movies.category', verbose_name='Catégories'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.DurationField(blank=True, help_text='Durée (heures et minutes) - Pour les films uniquement', null=True, verbose_name='Durée'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='En vedette'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='posters/', verbose_name='Affiche'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(verbose_name='Date de sortie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de la bande-annonce'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video_file',
            field=models.FileField(blank=True, help_text='Pour les films uniquement', null=True, upload_to='videos/', verbose_name='Fichier vidéo'),
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.PositiveIntegerField(verbose_name='Numéro de saison')),
                ('title', models.CharField(blank=True, help_text="Optionnel - ex: 'Saison 1: Les Origines'", max_length=200, verbose_name='Titre de la saison')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description de la saison')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Date de sortie de la saison')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='seasons/', verbose_name='Affiche de la saison')),
                ('series', models.ForeignKey(limit_choices_to={'content_type': 'series'}, on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='movies.movie', verbose_name='Série')),
            ],
            options={
                'verbose_name': 'Saison',
                'verbose_name_plural': 'Saisons',
                'ordering': ['series', 'season_number'],
                'unique_together': {('series', 'season_number')},
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.PositiveIntegerField(verbose_name="Numéro d'épisode")),
                ('title', models.CharField(max_length=200, verbose_name="Titre de l'épisode")),
                ('description', models.TextField(verbose_name='Description')),
                ('duration', models.DurationField(help_text="Durée de l'épisode (heures et minutes)", verbose_name='Durée')),
                ('video_file', models.FileField(upload_to='episodes/', verbose_name="Fichier vidéo de l'épisode")),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='episode_thumbnails/', verbose_name="Miniature de l'épisode")),
                ('air_date', models.DateField(blank=True, null=True, verbose_name='Date de diffusion')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name="Note de l'épisode")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='movies.season', verbose_name='Saison')),
            ],
            options={
                'verbose_name': 'Épisode',
                'verbose_name_plural': 'Épisodes',
                'ordering': ['season', 'episode_number'],
                'unique_together': {('season', 'episode_number')},
            },
        ),
    ]
